---
- hosts: all
  user: ubuntu
  become: yes  # this is to run tasks as sudo
  tasks:
    - name: Ensure curl and ufw are installed
      apt:
        name: ['curl', 'ufw']
        state: present

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Allow Apache through UFW
      ansible.builtin.ufw:
        rule: allow
        name: "Apache Full"

    - name: Insert content into index.html
      copy:
        content: "Hello world\n"
        dest: /var/www/html/index.html

    - name: Append instance IP to index.html
      shell:
        cmd: "echo $(curl http://169.254.169.254/latest/meta-data/local-ipv4) >> /var/www/html/index.html"
       